'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class testinputpagelol

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ddlCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCompanyName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtgbctype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtgbctype As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDateofIncorporation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateofIncorporation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCompanyNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBRN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTypeSpecialLicense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTypeSpecialLicense As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSpecialLicenseNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecialLicenseNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherStaturotyInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherStaturotyInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVatNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVatNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmpRegNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpRegNum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''hfCallBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCallBack As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtdatelstrocpayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatelstrocpayment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdatelstfscpayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatelstfscpayment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbalancesheetdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbalancesheetdate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtauditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtauditor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''xtxlastagmdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xtxlastagmdate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtlastannualreturnfiled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlastannualreturnfiled As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtlastaccountfiledwithroc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlastaccountfiledwithroc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdatefiledwithroc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatefiledwithroc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtlastaccountfiled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlastaccountfiled As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdatefiled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatefiled As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txttannumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttannumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtlasttaxreturnfiled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlasttaxreturnfiled As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txttrc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttrc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdateofexpirytrc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdateofexpirytrc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtaspfiled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaspfiled As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtlastvatreturned control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlastvatreturned As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtanyspecificclientinstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtanyspecificclientinstruction As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtothercompanyinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtothercompanyinfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdateassetinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdateassetinfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txttypeofasset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttypeofasset As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdetailofasset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdetailofasset As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvAssetInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvAssetInfo As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtdateotherissues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdateotherissues As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtissues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtissues As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtactionitems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtactionitems As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvOtherIssues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvOtherIssues As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtdetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdetails As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbrccode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbrccode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvBusinessActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvBusinessActivity As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtbeneficialowner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbeneficialowner As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvBeneficialOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvBeneficialOwner As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtdirectorname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdirectorname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdateofappointment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdateofappointment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvDirectors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvDirectors As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtnameofshareholder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnameofshareholder As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtnumberofshares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnumberofshares As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtpercentshareholdings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpercentshareholdings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtclassofshares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtclassofshares As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtstatedcapital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstatedcapital As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcomments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcomments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvShareholdings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvShareholdings As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtlastdporegistrationfiled control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlastdporegistrationfiled As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdpocertificatedate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdpocertificatedate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvDPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvDPO As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtbankname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbankname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbankaccountnumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbankaccountnumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcurrency As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbalance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbanksignatories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbanksignatories As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtsigningarrangement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsigningarrangement As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvBankAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvBankAccount As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtgoupmandate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtgoupmandate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gdvBankMandate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvBankMandate As Global.System.Web.UI.WebControls.GridView
End Class
